sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eGWtAVdXP3BbuTP7iLybm2iY5wtkT+Bq7RGX8oFX1wIuyyl6064cwV4RacPCWCHOVGYV5dlNi70mEFRToE/gtSCUMj/d0oKYIFYPPxJ/erxBVDjmQYKybTX743XskTVfIsuSQO4/uVJic/jkQBQUOVzEpamr0/zJ1p6FCBfdCdDuPsabah2bsfqG9p5FsV1wUsylwqYja+9LqBnLMWK9kkHKLQyE1FxqGjRm1Tbk7Hmr83qgjnXLnS/4FSYYyqd1+c0qDVmm9+kZxaUnfufINMHL3GTCVRAro9OiR+ohWBbsRRBpR3WZh8E9Bx3QiBdchBe4UfRVDRneh5GTguw3ol77sLzURAPqpDcH7hpW90Td5KrtTwl8AYta5jY5KivuKraRKtm5jw15bINoT1upgk2+TUtlDcnk/qNoSn2T4047OMKSHxY5sAkOiba78XW5KQBSTCxHd4A8SLVFm2mMlQzz5v03NyrYfhskZyUSgIXPp1FGq0q51YWnvDKlWvYNoPddWXzaQyjhSaenlIFD4ZTH8SNyhaIw11nOE2IVWfg5sv6bLY4vngxzGNLS0SGa0E65kOJAw1yD0e43WcsJsVPdBIZiiLpBGSBTh8A76oqIDbw4UV/MvX+Nm8DAzi+izeHgUcMoaqa1cNdSJXy4tGcrVTRhvFZ0qNePy2M+BGA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Second-Book-of-Operas_3770
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy